name: AWK CI

on:
  push:
    paths:
      - 'awk/**'
      - '.github/workflows/awk**'
  pull_request:
    paths:
      - 'awk/**'
      - '.github/workflows/awk**'

  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: One test FAILs
      working-directory: awk
      run: |
        rm -rf result.txt | true
        make test > result.txt
        grep "1 failed" result.txt

    - name: The others PASS
      working-directory: awk
      run: |
        rm -rf result.txt | true
        make test > result.txt
        grep "3 passed" result.txt
