name: C++ CI

on:
  push:
    paths:
      - 'cpp/googlemock/**'
      - '.github/workflows/cpp**'
  pull_request:
    paths:
      - 'cpp/googlemock/**'
      - '.github/workflows/cpp**'

  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:
  run:
    runs-on: ubuntu-latest
    name: C++ GoogleMock testing on ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get install -y clang libgmock-dev

      - name: test
        working-directory: cpp/googlemock
        run: make test_filterout_failing

      - name: assure one failing test
        working-directory: cpp/googlemock
        run: "sh ../../.scripts/assure_failing_test.sh './kata_tests' 'life_the_universe_and_everything'"

  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: docker googlemock
        working-directory: cpp/googlemock
        run: "sh ../../.scripts/assure_failing_test.sh './docker_test.sh' 'life_the_universe_and_everything'"
